version: '3.2'

services:
  rgb-node-0:
    container_name: rgb-node-0
    image: rgb-node:0.8
    build: .
    environment:
      MYUID: 1000
      MYGID: 1000
      RGB_ELECTRUM_SERVER: electrs:50001
    volumes:
      - ./data0:/var/lib/rgb
    working_dir: /var/lib/rgb
  rgb-node-1:
    container_name: rgb-node-1
    image: rgb-node:0.8
    build: .
    environment:
      MYUID: 1000
      MYGID: 1000
      RGB_ELECTRUM_SERVER: electrs:50001
    volumes:
      - ./data1:/var/lib/rgb
    working_dir: /var/lib/rgb
  rgb-node-2:
    container_name: rgb-node-2
    image: rgb-node:0.8
    build: .
    environment:
      MYUID: 1000
      MYGID: 1000
      RGB_ELECTRUM_SERVER: electrs:50001
    volumes:
      - ./data2:/var/lib/rgb
    working_dir: /var/lib/rgb
  bitcoind:
    container_name: rgb-bitcoind
    image: registry.gitlab.com/hashbeam/docker/bitcoind:23.0
    command: "-fallbackfee=0.0002"
    environment:
      MYUID: 1000
      MYGID: 1000
    volumes:
      - ./datacore:/srv/app/.bitcoin
  electrs:
    container_name: rgb-electrs
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.9
    environment:
      MYUID: 1000
      MYGID: 1000
    volumes:
      - ./dataindex:/srv/app/db
    depends_on:
      - bitcoind
    ports:
      - 50001:50001
